import { parser } from "@/utils/parser";
import Head from "next/head";
import { ChangeEvent } from "react";

export default function Home() {
  function handleChange(event: ChangeEvent<HTMLInputElement>) {
    parser(event.target.value)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input type="text" defaultValue="* * * * * *" onChange={handleChange} />
    </>
  );
}
