import { parser } from "@/utils/parser";
import Head from "next/head";
import { ChangeEvent, useState } from "react";

export default function Home() {
  const [status, setStatus] = useState(false)

  function handleChange(event: ChangeEvent<HTMLInputElement>) {
    const result = parser(event.target.value)
    setStatus(result)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input type="text" defaultValue="* * * * * *" onChange={handleChange} style={{ borderColor: status ? 'green' : 'red'}} />
    </>
  );
}
